### ISSUE TITLE
Geslo za bazo

### ISSUE THREAD

**Issue by jaanos** [15minutOdmora/Generator-filmov#2]
Vidim, da imata v `dbCommunication.py` geslo za prijavo na bazo, kar z varnostnega vidika ni najbolj priporočljivo (sploh, če je mogoče do strežnika dostopati od zunaj). Svetujem torej, da geslo zamenjata, podatki za povezavo pa naj bodo npr. v datoteki `auth.py`, ki pa naj je ne bo na repozitoriju - v ta namen dodajta ustrezno vrstico v `.gitignore`, da je ne bosta po nesreči dodala (seveda poskrbita, da bo datoteka prisotna na strežniku, kjer bo tekel program). Potem imata lahko v `auth.py` nekaj takega:

```python
AUTH = {
    "host": "generator-filmov-1.cay847edpwb1.us-east-2.rds.amazonaws.com",
    "user": "admin",
    "passwd": "spremenjenogeslo",
    "database": "mydb"
}
```

V `dbCommunication.py` se lahko potem na bazo povežeta tako:

```python
import mysql.connector
from auth import AUTH


class Connector:
    def __init__(self):
        self.db = mysql.connector.connect(**AUTH)
        self.cur = None

    ...
```

**Comment by 15minutOdmora** [comment]
Popravljeno.
